apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: 'https://gitlab.com/microservices6813119/microservices-k8s-manifests.git'
    path: microservices
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
