apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: mohamedsamirebrahim/microservices-python-image
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: microservices
  source:
    repoURL: 'https://gitlab.com/microservices6813119/microservices-k8s-manifests.git'
    path: microservices
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
