apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mohamedsamirspot/Microservices-K8s-Manifests.git'
    path: root
    targetRevision: HEAD
    directory:
      recurse: true    # << important
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
