apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-prod
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: ghcr.io/mohamedsamirspot
    chart: microservices-app
    targetRevision: 1.0.1
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
