apiVersion: v1
kind: Secret
metadata:
  name: microservices-helm-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: ghcr-microservices
  url: ghcr.io/mohamedsamirspot
  enableOCI: "true"
  project: microservices