apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: microservices
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Microservices
  destinations:
    - name: in-cluster
      namespace: microservices-prod
      server: https://kubernetes.default.svc
    - namespace: microservices-dev
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/mohamedsamirspot/Microservices-K8s-Manifests.git
