apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "microservices.labels"  .  | nindent 4}}
spec:
  refreshPolicy: Periodic
  refreshInterval: 30s  # Update every hour
  secretStoreRef:
    name: clustersecretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secret.name }}
  dataFrom:
    - extract:
        key: microservices-secret-2
