helm:
  parameters:
  - name: app.image.repository
    value: mohamedsamirebrahim/microservices-python-image
    forcestring: true
  - name: app.image.tag
    value: dev-51
    forcestring: true
  - name: app.image.name
    value: mohamedsamirebrahim/microservices-python-image
    forcestring: true
